[openai]
api_key="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"
[vector_store]
id="vs_67dc01408d2c8191ab6a03128a05f4e0"